EFDBContextExample/Controllers/LogController.cs
using Entity;
using DALServices.Interfaces;
using Ninject;
using System.Collections.Generic;
using System.Reflection;
using System.Web.Mvc;

namespace EFDBContextExample.Controllers
{
    public class LogController : Controller
    {
        private readonly IUserLog userlog;
        //private readonly IRepository<UserLog> logs;

        public LogController()
        {
            StandardKernel _kernal = new StandardKernel();
            _kernal.Load(Assembly.GetExecutingAssembly());
            IUserLog ulog = _kernal.Get<IUserLog>();
            this.userlog = ulog;
        }

        public ActionResult Index()
        {
            InputParameters param = new InputParameters();
            param.StartDate = string.Empty;
            param.EndDate = string.Empty;

            List<UserLog> result = userlog.GetLogData(param);
            return View(result);
        }
    }
}

EFDBContextExample/Controllers/UserLogController.cs
using Entity;
using DALServices.Interfaces;
using System.Web.Mvc;
using Ninject;
using System.Reflection;
using System.Collections.Generic;

namespace EFDBContextExample.Controllers
{
    public class UserLogController : Controller
    {
        // GET: UserLog
        private readonly IUserLog userlog;
        //private readonly IRepository<UserLog> logs;

        public UserLogController()
        {
            StandardKernel _kernal = new StandardKernel();
            _kernal.Load(Assembly.GetExecutingAssembly());
            IUserLog ulog = _kernal.Get<IUserLog>();
            this.userlog = ulog;
        }

        public ActionResult Index(InputParameters param = null)
        {
            return View(userlog.GetLog(param));
        }

        //public LogModel GetLogData(int currentPage)
        //{
        //    InputParameters param = new InputParameters();
        //    param.TotalRow = 10;
        //    param.PageNo = currentPage;
        //    param.IsSearch = false;
        //    //param.StartDate = string.Empty;
        //    //param.EndDate= string.Empty;
        //    //param.Level = string.Empty;
        //    //param.UserId = string.Empty;
        //    //param.Id = 0;
        //    //double pageCount = (double)((decimal)userlog.Count() / Convert.ToDecimal(maxRows));
        //    //LogModel.PageCount = (int)Math.Ceiling(pageCount);

        //    LogModel result = new LogModel();
        //    result = userlog.GetLog(param);
        //    return result;
        //}

        public JsonResult GetLogDetail(int id)
        {
            return Json(userlog.GetLogDetail(id), JsonRequestBehavior.AllowGet);
        }

        public JsonResult SearchErrorLogs(InputParameters searchParam)
        {
            return Json(userlog.GetLog(searchParam), JsonRequestBehavior.AllowGet);
        }
    }
}

EFDBContextExample/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

EFDBContextExample/Views/UserLog/GetloggingData.cshtml
@model Entity.LogModel

@using (Html.BeginForm("GetloggingData", "UserLog", FormMethod.Post, new { id = "myForm" }))
{
    
    <div class="row">
        <div class="col-md-3">
            <button type="submit" class="btn btn-warning" id="btnSearch" name="btnSearch" onclick="sendData()">Search</button>
            @* onclick="SearchErrorLogs();" *@
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-md-12 table-responsive">
            <h4>Log</h4>
            <hr />

            <table cellpadding="0" cellspacing="0" class="table">
                <tr>
                    <th>Id</th>
                    <th>Host</th>
                    <th>Error</th>
                    <th>Operation</th>
                </tr>
                @foreach (var item in Model.Data)
                {
                    <tr>
                        <td>@item.Id</td>
                        <td>@item.Host</td>
                        <td>@item.Error</td>
                        <td><a href="JavaScript:void(0);" onclick="GetErrorById(@item.Id)">View Error</a></td>
                    </tr>
                }
            </table>
            <br />
            <table cellpadding="0" cellspacing="0">
                <tr>
                    @for (int i = 1; i <= Model.PageCount; i++)
                    {
                        <td>
                            @if (i != Model.CurrentPageIndex)
                            {
                                <a href="javascript:PagerClick(@i);">@i</a>
                            }
                            else
                            {
                                <span>@i</span>
                            }
                        </td>
                    }
                </tr>
            </table>
            <input type="hidden" id="hfCurrentPageIndex" name="PageNo" value="1" />
            <input type="hidden" id="hfIsSearch" name="IsSearch" value="false" />

            <script type="text/javascript">
                function PagerClick(index) {

                    document.getElementById("hfCurrentPageIndex").value = index;
                    sendData();
                }
            </script>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-md-12">
            <b>
                <span id="Host"></span>
            </b>

            <br />
            <br />
            <span id="FullError"></span>
        </div>
    </div>
}

EFDBContextExample/Views/UserLog/Index.cshtml
@using Entity
@model Entity.LogModel
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <style type="text/css">
        body {
            font-family: Arial;
            font-size: 10pt;
        }

        table {
            border: 1px solid #ccc;
            border-collapse: collapse;
            background-color: #fff;
        }

            table th {
                background-color: #B8DBFD;
                color: #333;
                font-weight: bold;
            }

            table th, table td {
                padding: 5px;
                border: 1px solid #ccc;
            }

            table, table table td {
                border: 0px solid #ccc;
            }
    </style>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/css/datepicker.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.8.1/css/bootstrap-select.css">
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.8.1/js/bootstrap-select.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/js/bootstrap-datepicker.js"></script>
</head>
<body>


    <div class="container">

        @using (Html.BeginForm("Index", "UserLog", FormMethod.Post, new { id = "myForm" }))
        {
            <br />
            <br />
            <div class="row">
                <div class="col-md-3">
                    <div class="form-group">
                        <label for="StartDate">Start date:</label>
                        <input type="text" value="" id="startDate" name="StartDate" class="form-control datepicker" />
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        <label for="EndDate">End date:</label>
                        <input type="text" value="" id="endDate" name="EndDate" class="form-control datepicker" />
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        <label for="EndDate">Error level:</label>
                        @Html.DropDownList("errorLevel", EnumHelper.GetSelectList(typeof(Enumeration.ErrorLevel)),
                            "Select error level",new { multiple = "multiple", @class = "form-control selectpicker", @data_live_search = "true" })

                        <input type="hidden" id="Level" name="Level" value="" />
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        <label for="UserId">UserId:</label>
                        <input type="text" value="" id="userId" name="UserId" class="form-control" />
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    <button type="button" class="btn btn-warning" id="btnSearch" name="btnSearch" onclick="$('#hfIsSearch').val(true); $('#hfCurrentPageIndex').val(1); GetErrorLogs();">Search</button>
                    @* onclick="SearchErrorLogs();" *@
                </div>
            </div>
            <br />

            <div class="row">
                <div class="col-md-12 table-responsive">
                    <h4>Log</h4>
                    <hr />

                    <table cellpadding="0" cellspacing="0" class="table">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>Host</th>
                                <th>Error</th>
                                <th>Operation</th>
                            </tr>
                        </thead>
                        <tbody id="loggDataTable">
                            @foreach (var item in Model.Data)
                            {
                                <tr>
                                    <td>@item.Id</td>
                                    <td>@item.Host</td>
                                    <td>@item.Error</td>
                                    <td><a href="JavaScript:void(0);" onclick="GetErrorById(@item.Id)">View Error</a></td>
                                </tr>
                            }
                        </tbody>
                    </table>
                    <br />
                    <table cellpadding="0" cellspacing="0" id="paging">
                        <tr>
                            @for (int i = 1; i <= Model.PageCount; i++)
                            {
                                <td>
                                    @if (i != Model.CurrentPageIndex)
                                    {
                                        <a href="javascript:PagerClick(@i);">@i</a>
                                    }
                                    else
                                    {
                                        <span>@i</span>
                                    }
                                </td>
                            }
                        </tr>
                    </table>
                    <input type="hidden" id="hfCurrentPageIndex" name="PageNo" value="1" />
                    <input type="hidden" id="hfIsSearch" name="IsSearch" value="false" />

                    <script type="text/javascript">
                        function PagerClick(index) {
                            document.getElementById("hfCurrentPageIndex").value = index;
                            GetErrorLogs();
                        }
                    </script>
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-md-12">
                    <b>
                        <span id="Host"></span>
                    </b>

                    <br />
                    <br />
                    <span id="FullError"></span>
                </div>
            </div>
        }
    </div>

    <script>

        $(function () {
            $("#startDate").datepicker({
                todayBtn: 1,
                autoclose: true,
            }).on('changeDate', function (selected) {
                debugger
                var minDate = new Date(selected.date.valueOf());
                $('#endDate').datepicker('setStartDate', minDate);
                $('#endDate').datepicker('setDate', minDate); // <--THIS IS THE LINE ADDED
            });

            $("#endDate").datepicker()
                .on('changeDate', function (selected) {
                    var maxDate = new Date(selected.date.valueOf());
                    $('#startDate').datepicker('setEndDate', maxDate);
                });

        });

        $(document).ready(function () {
            $('#hfIsSearch').val(false);
            $('select').selectpicker();
        });

        function sendData() {
            if ('Nothing selected' != $('button[data-id=errorLevel]').attr('title')) {
                $('#Level').val($('button[data-id=errorLevel]').attr('title'));
            }
            else {
                $('#Level').val('');
            }
            $('#hfIsSearch').val(true);
            $("#myForm").submit();
        }

        function GetErrorById(id) {
            $.ajax({
                url: '/UserLog/GetLogDetail',
                type: 'GET',
                data: { 'id': id },
                dataType: 'json',
                success: function (data) {
                    debugger
                    //alert('Data: ' + data);
                    $('#Host').html(data.Host);
                    $('#FullError').html(data.Error);
                },
                error: function (request, error) {
                    alert("Request: " + JSON.stringify(request));
                }
            });
        }

        function GetErrorLogs() {

            var levelData = "";
            if ('Nothing selected' != $('button[data-id=errorLevel]').attr('title')) {
                levelData = $('button[data-id=errorLevel]').attr('title');
            }

            var searchParam = JSON.stringify({
                StartDate: $('#startDate').val(),
                EndDate: $('#endDate').val(),
                Level: levelData,
                UserId: $('#userId').val(),
                IsSearch: $('#hfIsSearch').val(),
                PageNo: $('#hfCurrentPageIndex').val()
            });

            $('#loggDataTable').html('');
            $.ajax({
                url: '/UserLog/SearchErrorLogs',
                type: 'POST',
                data: searchParam,
                contentType: "application/json; charset=utf-8",
                dataType: 'json',
                success: function (data) {
                    debugger
                    $('#paging').html('');

                    var pagingHtml = "<tr>";
                    for (var i=1; i <= data.PageCount; i++)
                    {
                        pagingHtml += "<td>";
                        if (i != data.CurrentPageIndex)
                        {
                            pagingHtml += "<a href='javascript:PagerClick("+i+");'>" + i + "</a>";
                        }
                        else
                        {
                            pagingHtml += "<span>"+i+"</span>";
                        }
                        pagingHtml += "</td>";
                    }
                    pagingHtml += "</tr>";
                    $('#paging').html(pagingHtml);

                    var renderHtml = '';
                    $.each(data.Data, function (key, value) {
                        renderHtml += '<tr><td>' + value.Id +'</td>';
                        renderHtml += '<td>' + value.Host +'</td>';
                        renderHtml += '<td>' + value.Error +'</td>';
                        renderHtml += '<td><a href="JavaScript:void(0);" onclick="GetErrorById('+ value.Id +')">View Error</a></td></tr>';
                    });
                    if (renderHtml == '') {
                        renderHtml += '<tr><td colspan=4>No data found...!</td></tr>'
                    }
                    $('#loggDataTable').html(renderHtml);
                },
                error: function (request, error) {
                    alert("Request: " + JSON.stringify(request));
                }
            });
        }

    </script>
</body>
</html>

EFDBContextExample/Views/UserLog/UserLog.cshtml
@using Entity

@model LogModel

@{
    ViewBag.Title = "UserLog";
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <style type="text/css">
        body {
            font-family: Arial;
            font-size: 10pt;
        }

        table {
            border: 1px solid #ccc;
            border-collapse: collapse;
            background-color: #fff;
        }

            table th {
                background-color: #B8DBFD;
                color: #333;
                font-weight: bold;
            }

            table th, table td {
                padding: 5px;
                border: 1px solid #ccc;
            }

            table, table table td {
                border: 0px solid #ccc;
            }
    </style>
</head>
<body>
    <div>
        @using (Html.BeginForm("Index", "UserLog", FormMethod.Post))
        {
            <h4>Log</h4>
            <hr />
            <table cellpadding="0" cellspacing="0">
                <tr>
                    <th>CustomerID</th>
                    <th>ContactName</th>
                    <th>City</th>
                    <th>Country</th>
                </tr>
                @foreach (UserLog item in Model.Data)
                {
                <tr>
                    <td>@item.Id</td>
                    <td>@item.Host</td>
                    <td>@item.Error</td>
                </tr>
                }
            </table>
            <br />
            <table cellpadding="0" cellspacing="0">
                <tr>
                    @for (int i = 1; i <= Model.PageCount; i++)
                    {
                        <td>
                            @if (i != Model.CurrentPageIndex)
                            {
                                <a href="javascript:PagerClick(@i);">@i</a>
                            }
                            else
                            {
                                <span>@i</span>
                            }
                        </td>
                    }
                </tr>
            </table>
            <input type="hidden" id="hfCurrentPageIndex" name="currentPageIndex" />
        }
        <script type="text/javascript">
            function PagerClick(index) {
                document.getElementById("hfCurrentPageIndex").value = index;
                document.forms[0].submit();
            }
        </script>
    </div>
</body>
</html>